- hosts: ubu_zabcl
  become: yes
  tasks:

  - name: Install zabbix-agent repo on Ubuntu
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb

  - name: Install zabbix-agent2 on Ubuntu
    ansible.builtin.apt:
      name: zabbix-agent2
      state: present
      update_cache: yes

  - name: Copy config Ubuntu
    ansible.builtin.template:
      src: /etc/ansible/common/files/zabbix_agent2.conf
      dest: /etc/zabbix/zabbix_agent2.conf
      owner: root
      group: root
      mode: '0644'


  - name: enable zabbix-agent2 on Ubuntu    
    ansible.builtin.service:
      state: restarted
      name: zabbix-agent2
      enabled: true

- hosts: cent_zabcl
  become: yes
  tasks:

  - name: Install zabbix-agent repo on CentOS
    ansible.builtin.yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-6.4-1.el7.noarch.rpm    

  - name: Install zabbix-agent2 on CentOS
    ansible.builtin.yum:
      name: zabbix-agent2
      state: present
      update_cache: yes

  - name: Copy config CentOS
    ansible.builtin.template:
      src: /etc/ansible/common/files/zabbix_agent2.conf
      dest: /etc/zabbix/zabbix_agent2.conf
      owner: root
      group: root
      mode: '0644'

  - name: enable zabbix-agent2 on CentOS
    ansible.builtin.service:
      state: restarted 
      name: zabbix-agent2
      enabled: true

